site_name: Technical Documenation
theme:
  name: material
  
nav:
    - Home: 'index.md'
    - Elastic Stack: 
        - Part 1 Introduction: 'elastic-stack/Part1-Introduction.md'
        - Part 2 Local Installation: 'elastic-stack/Part2-LocalInstallation.md'
        - Part 3 Reading JSON from file with LogStash: 'elastic-stack/Part3-JsonFromFile.md'
        - Part 4 Reading JSON from a TCP connection with LogStash: 'elastic-stack/Part4-JsonOverTcp.md'
        - Part 5 Example 1 plotting trig functions in Kibana: 'elastic-stack/Part5-Example1-trig.md'
        - Part 6 Elasticsearch mappings and templates: 'elastic-stack/Part6-ElasticMappings.md'
        - Part 7 Server deployment: 'elastic-stack/Part7-ServerDeployment.md'
        
# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
